version: '3.6'
services:
  # mongo:
  #   image: "mongo:latest"
  #   ports:
  #     - "27017:27017"

  viewer:
    image: thiagosena/viewer:latest
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/nuclearis
    extra_hosts:
      - "pacsIP:192.168.0.2"
    volumes:
      - ./dockersupport/app.json:/app/app.json